weights: yolov5n.pt
cfg: models/yolov5n_kaist-rgbt.yaml
data: data/kaist-rgbt.yaml
hyp:
  lr0: 0.001
  lrf: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  warmup_epochs: 20.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.1
  cls: 0.3
  cls_pw: 1.0
  obj: 1.0
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0.0
  hsv_s: 0.0
  hsv_v: 0.0
  degrees: 0.0
  translate: 0.1
  scale: 0.0
  shear: 0.0
  perspective: 0.0001
  flipud: 0.0
  fliplr: 0.5
  mosaic: 0.5
  mixup: 0.0
  copy_paste: 0.05
  class_weights:
  - 1.0
  - 0.8
  - 0.9
  - 0.6
  small_object_weight: 1.5
  fusion_weight_rgb: 0.6
  fusion_weight_thermal: 0.4
  low_light_enhancement: true
  thermal_noise_std: 15.0
epochs: 24
batch_size: 8
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
evolve_population: data/hyps
resume_evolve: null
bucket: ''
cache: null
device: ''
multi_scale: false
single_cls: true
optimizer: SGD
sync_bn: false
workers: 8
project: aue8088_final_project
name: yolov5n_hyps_singleclass
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
save_period: -1
seed: 0
local_rank: -1
rgbt: true
entity: chanwookim01-hanyang-university
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
is_train: true
save_dir: aue8088_final_project/yolov5n_hyps_singleclass
